services:
  php_backend:
    build:
      context: ./php_backend
      dockerfile: Dockerfile
    volumes:
      - ./php_backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - PHP_ENV=development

  web_frontend:
    build:
      context: ./web_frontend
      dockerfile: Dockerfile
    volumes:
      - ./web_frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - php_backend
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

volumes:
  node_modules:




   